services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # 修改为3000端口
    networks:
      - herbal-network
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10010:10010"
    networks:
      - herbal-network

networks:
  herbal-network:
    driver: bridge
